import os

L = []
L.append('<!DOCTYPE html>')
L.append('<html lang="zh-CN">')
L.append('<head><meta charset=UTF-8><title>V3.3.3-Core</title><style>')
L.append('*{margin:0;padding:0;box-sizing:border-box;}')
L.append('body{font-family:sans-serif;background:linear-gradient(135deg,#0f0c29,#302b63,#24243e);min-height:100vh;color:#e0e0e0;padding:20px;}')
L.append('h1{text-align:center;color:#e94560;margin-bottom:20px;}')
L.append('table{width:100%;border-collapse:collapse;background:#16213e;border-radius:8px;overflow:hidden;}')
L.append('th{background:#0f3460;padding:8px 6px;font-size:12px;text-align:left;}')
L.append('td{padding:8px 6px;border-bottom:1px solid #1a1a2e;font-size:13px;}')
L.append('tr:hover td{background:rgba(255,255,255,0.03);}')
L.append('.detail-row{display:none;}.detail-row.show{display:table-row;}')
L.append('.detail-box{padding:12px 16px;background:rgba(15,52,96,0.3);font-size:12px;line-height:1.7;}')
L.append('.badge{display:inline-block;padding:2px 8px;border-radius:4px;font-size:11px;font-weight:bold;}')
L.append('.badge-s{background:rgba(13,71,161,0.3);color:#64b5f6;}')
L.append('.badge-a{background:rgba(230,81,0,0.3);color:#ffab40;}')
L.append('.badge-b{background:rgba(46,125,50,0.3);color:#81c784;}')
L.append('.badge-c{background:rgba(120,120,120,0.3);color:#aaa;}')
L.append('.prob-bar-wrap{display:flex;height:12px;background:rgba(255,255,255,0.1);border-radius:4px;overflow:hidden;margin-top:2px;}')
L.append('.prob-bar-home{background:#66bb6a;height:100%;}')
L.append('.prob-bar-draw{background:#ffa726;height:100%;}')
L.append('.prob-bar-away{background:#ef5350;height:100%;}')
L.append('</style></head><body><div style=max-width:1400px;margin:0 auto;>')
L.append('<h1>V3.3.3-Core \u8db3\u7403\u91cf\u5316\u5206\u6790\u7cfb\u7edf</h1>')
L.append('<div id=result></div></div><script>')

# JS
L.append('function bg(r,f){')
L.append("if(r==='S')return'<span class=\"badge badge-s\">S\u7ea7</span>'")
L.append("if(r==='A')return'<span class=\"badge badge-a\">A\u7ea7</span>'")
L.append("if(r==='C')return'<span class=\"badge badge-c\">C\u7ea7</span>'")
L.append("if(f>=9)return'<span class=\"badge badge-s\">S\u7ea7</span>'")
L.append("if(f>=7)return'<span class=\"badge badge-a\">A\u7ea7</span>'")
L.append("if(f>=5)return'<span class=\"badge badge-b\">B\u7ea7</span>'")
L.append("return'<span class=\"badge badge-c\">C\u7ea7</span>'}")

L.append('function rs(d){')
L.append('var r=d.rating,mi=d.info||[],a2=d.ddi||[],a3=d.ai||[],a4=d.mc||[];')
L.append('var im={},dm={},am={},mm={};')
L.append('mi.forEach(function(m){im[m.id]=m;});')
L.append('a2.forEach(function(m){dm[m.id]=m;});')
L.append('a3.forEach(function(m){am[m.id]=m;});')
L.append('a4.forEach(function(m){mm[m.id]=m;});')
L.append('var s=[].concat(r).sort(function(a,b){return a.id.localeCompare(b.id);});')
L.append("var h='<table><thead><tr><th>\u7f16\u53f7</th><th>\u65f6\u95f4</th><th>\u5bf9\u9635</th><th>\u65b9\u5411</th><th>\u6982\u7387</th><th>&lambda;</th><th>DDI</th><th>S7</th><th>\u76d8\u53e3</th><th>\u8bc4\u5206</th><th>\u8bc4\u7ea7</th><th></th></tr></thead><tbody>';")

L.append('s.forEach(function(x){')
L.append('var m=im[x.id]||{},mc2=mm[x.id]||{},dr=dm[x.id]||{},ar=am[x.id]||{};')
L.append('var p=mc2.physical||{};')
L.append('var hw=(p.home_win||0)*100,dw=(p.draw||0)*100,aw=(p.away_win||0)*100;')
L.append('var dh=(dr.ddi||{}).home_win||0,s7=ar.s7_score||0;')
L.append('var lh=mc2.lambda_h_final||0,la=mc2.lambda_a_final||0;')
L.append('var ah=m.asian_handicap||0;')
L.append("var hs=ah===0?'0':(ah>0?'+'+ah.toFixed(1):ah.toFixed(1));")
L.append("var tm=m.time||'',ko=tm.length>=16?tm.substring(5,10)+'/'+tm.substring(11,16):'';")
L.append("var did='d'+x.id;")
L.append("var pb='<div>'+Math.round(hw)+'/'+Math.round(dw)+'/'+Math.round(aw)+'</div>';")
L.append("pb+='<div class=prob-bar-wrap>';")
L.append("pb+='<span class=prob-bar-home style=width:'+hw+'%></span>';")
L.append("pb+='<span class=prob-bar-draw style=width:'+dw+'%></span>';")
L.append("pb+='<span class=prob-bar-away style=width:'+aw+'%></span>';")
L.append("pb+='</div>';")
L.append("var ds='<span>'+(dh>=0?'+'+dh.toFixed(3):dh.toFixed(3))+'</span>';")
L.append("var ss=s7>0?'<span>'+s7+'</span>':'<span>0</span>';")
L.append("h+='<tr data-did='+did+'>';")
L.append("h+='<td>'+x.id+'</td><td>'+ko+'</td><td>'+x.home+' vs '+x.away+'</td>';")
L.append("h+='<td><b>'+x.direction+'</b></td><td>'+pb+'</td>';")
L.append("h+='<td>'+lh.toFixed(2)+'/'+la.toFixed(2)+'</td>';")
L.append("h+='<td>'+ds+'</td><td>'+ss+'</td><td>'+hs+'</td>';")
L.append("h+='<td>'+x.fit_score.toFixed(1)+'</td>';")
L.append("h+='<td>'+bg(x.rating,x.fit_score)+'</td>';")
L.append("h+='<td>\u25bc</td></tr>';")
L.append("var trap=ar.trap_analysis||'',risk=ar.key_risk||'',s7r=ar.s7_reason||'',ld=mc2.lambda_diff||0;")
L.append("h+='<tr class=detail-row id='+did+'>';")
L.append("h+='<td colspan=12><div class=detail-box>';")
L.append("h+='<b>\u03bb\u5dee\u503c:</b> '+ld.toFixed(3);")
L.append("if(s7r)h+='<br><b>S7\u8bf4\u660e:</b> '+s7r")
L.append("if(trap)h+='<br><b>\u8bf1\u76d8\u5206\u6790:</b> '+trap")
L.append("if(risk)h+='<br><b style=color:red>\u98ce\u9669\u63d0\u793a:</b> '+risk")
L.append("h+='</div></td></tr>'")
L.append('});')
L.append("h+='</tbody></table>';")
L.append('document.getElementById("result").innerHTML=h;')
L.append("document.getElementById('result').addEventListener('click',function(e){")
L.append("var tr=e.target.closest('tr[data-did]');if(tr){var id=tr.getAttribute('data-did');var dt=document.getElementById(id);if(dt)dt.classList.toggle('show');}")
L.append("});")
L.append('}')

L.append("window.onload=function(){fetch('/api/latest').then(function(r){return r.json();}).then(function(d){if(d.rating&&d.rating.length>0)rs(d);}).catch(function(){});};")
L.append('</script></body></html>')

with open('C:/Users/gjj/Desktop/v333/templates/index.html','w',encoding='utf-8') as f:
    f.write('\n'.join(L))
print('OK:',len('\n'.join(L)))
