import os

html = []
html.append('<!DOCTYPE html>')
html.append('<html lang="zh-CN">')
html.append('<head>')
html.append('<meta charset="UTF-8">')
html.append('<meta name="viewport" content="width=device-width, initial-scale=1.0">')
html.append('<title>V3.3.3-Core</title>')
html.append('<style>')
html.append('*{margin:0;padding:0;box-sizing:border-box;}')
html.append('body{font-family:-apple-system,BlinkMacSystemFont,"Microsoft YaHei",sans-serif;background:linear-gradient(135deg,#0f0c29,#302b63,#24243e);min-height:100vh;color:#e0e0e0;padding:20px;}')
html.append('h1{text-align:center;color:#e94560;margin-bottom:20px;font-size:22px;}')
html.append('table{width:100%;border-collapse:collapse;background:#16213e;border-radius:8px;overflow:hidden;}')
html.append('th{background:#0f3460;padding:8px 6px;font-size:12px;text-align:left;white-space:nowrap;}')
html.append('td{padding:8px 6px;border-bottom:1px solid #1a1a2e;font-size:13px;}')
html.append('tr:hover td{background:rgba(255,255,255,0.03);}')
html.append('.badge{display:inline-block;padding:2px 8px;border-radius:4px;font-size:11px;font-weight:bold;}')
html.append('.badge-s{background:rgba(13,71,161,0.3);color:#64b5f6;border:1px solid rgba(13,71,161,0.5);}')
html.append('.badge-a{background:rgba(230,81,0,0.3);color:#ffab40;border:1px solid rgba(230,81,0,0.5);}')
html.append('.badge-b{background:rgba(46,125,50,0.3);color:#81c784;border:1px solid rgba(46,125,50,0.5);}')
html.append('.badge-c{background:rgba(120,120,120,0.3);color:#aaa;border:1px solid rgba(120,120,120,0.5);}')
html.append('.detail-row{display:none;}.detail-row.show{display:table-row;}')
html.append('.detail-box{padding:12px 16px;background:rgba(15,52,96,0.3);font-size:12px;line-height:1.7;}')
html.append('.clickable{cursor:pointer;}')
html.append('.prob-bar-wrap{background:rgba(255,255,255,0.1);border-radius:4px;height:12px;overflow:hidden;margin-top:2px;display:flex;}')
html.append('.prob-bar{height:100%;}')
html.append('.prob-home{background:#66bb6a;}.prob-draw{background:#ffa726;}.prob-away{background:#ef5350;}')
html.append('</style>')
html.append('</head>')
html.append('<body>')
html.append('<div style="max-width:1400px;margin:0 auto;">')
html.append('<h1>V3.3.3-Core \u8db3\u7403\u91cf\u5316\u5206\u6790\u7cfb\u7edf</h1>')
html.append('<div id="result"></div>')
html.append('</div>')

# JavaScript
html.append('<script>')

# badge function
html.append('function bg(r,f){')
html.append('if(r==="S"){return\'<span class="badge badge-s">S\u7ea7</span>\'}')
html.append('if(r==="A"){return\'<span class="badge badge-a">A\u7ea7</span>\'}')
html.append('if(r==="C"){return\'<span class="badge badge-c">C\u7ea7</span>\'}')
html.append('if(f>=9){return\'<span class="badge badge-s">S\u7ea7</span>\'}')
html.append('if(f>=7){return\'<span class="badge badge-a">A\u7ea7</span>\'}')
html.append('if(f>=5){return\'<span class="badge badge-b">B\u7ea7</span>\'}')
html.append('return\'<span class="badge badge-c">C\u7ea7</span>\'}')

html.append('function s7c(s){return s>=1?"s7-warn":(s>=0.5?"s7-mid":"s7-safe")}')
html.append('function ddic(v){return Math.abs(v)>0.05?"ddi-trigger":"ddi-normal"}')
html.append('function td(i){var e=document.getElementById(i);if(e)e.classList.toggle("show")}')

# renderSummary
html.append('function rs(d){')
html.append('var r=d.rating;var mi=d.info||[];var dd=d.ddi||[];var ai=d.ai||[];var mc=d.mc||[];')
html.append('var im={},dm={},am={},mm={};')
html.append('mi.forEach(function(m){im[m.id]=m;});')
html.append('dd.forEach(function(m){dm[m.id]=m;});')
html.append('ai.forEach(function(m){am[m.id]=m;});')
html.append('mc.forEach(function(m){mm[m.id]=m;});')
html.append('var sorted=[].concat(r).sort(function(a,b){return a.id.localeCompare(b.id);});')
html.append('var h=\'<table><thead><tr><th>\u7f16\u53f7</th><th>\u65f6\u95f4</th><th>\u5bf9\u9635</th><th>\u65b9\u5411</th><th>\u6982\u7387\u5206\u5e03</th><th>\u03bb\u4e3b/\u5ba2</th><th>DDI</th><th>S7</th><th>\u76d8\u53e3</th><th>\u8d34\u5408\u5ea6</th><th>\u8bc4\u7ea7</th><th></th></tr></thead><tbody>\';')

html.append('sorted.forEach(function(x){')
html.append('var m=im[x.id]||{};var mc2=mm[x.id]||{};var dr=dm[x.id]||{};var ar=am[x.id]||{};')
html.append('var p=mc2.physical||{};')
html.append('var hw=(p.home_win||0)*100;var dw=(p.draw||0)*100;var aw=(p.away_win||0)*100;')
html.append('var dh=(dr.ddi||{}).home_win||0;')
html.append('var s7=ar.s7_score||0;')
html.append('var lh=mc2.lambda_h_final||0;var la=mc2.lambda_a_final||0;')
html.append('var ah=m.asian_handicap||0;')
html.append('var hs=ah===0?"0":(ah>0?"+"+ah.toFixed(1):ah.toFixed(1));')
html.append('var tm=m.time||"";var ko=tm.length>=16?tm.substring(5,10)+"/"+tm.substring(11,16):"";')
html.append('var did="d"+x.id;')

# prob bar
html.append('var pb="<div style=\\"font-size:10px;color:#aaa;\\">"+Math.round(hw)+"/"+Math.round(dw)+"/"+Math.round(aw)+"</div>";')
html.append('pb+="<div class=\\"prob-bar-wrap\\">";')
html.append('pb+="<span class=\\"prob-bar prob-home\\" style=\\"width:"+hw+"%;\\"></span>";')
html.append('pb+="<span class=\\"prob-bar prob-draw\\" style=\\"width:"+dw+"%;\\"></span>";')
html.append('pb+="<span class=\\"prob-bar prob-away\\" style=\\"width:"+aw+"%;\\"></span>";')
html.append('pb+="</div>";')

html.append('var ds="<span class=\\"quot;+ddic(dh)+"\\">quot;+(dh>=0?"+"+dh.toFixed(3):dh.toFixed(3))+"</span>";')
html.append('var ss=s7>0?"<span class=\\"quot;+s7c(s7)+"\\">quot;+s7+"</span>":"<span>0</span>";')

# Main row
html.append('h+="<tr class=\\"clickable\\" onclick=\\"td(\\\'"+did+"\\\')\\">";')
html.append('h+="<td>"+x.id+"</td><td>"+ko+"</td><td>"+x.home+" vs "+x.away+"</td>";')
html.append('h+="<td><b>"+x.direction+"</b></td><td style=\\"min-width:140px;\\">"+pb+"</td>";')
html.append('h+="<td style=\\"font-size:11px;\\">quot;+lh.toFixed(2)+"/"+la.toFixed(2)+"</td>";')
html.append('h+="<td>"+ds+"</td><td>"+ss+"</td><td>"+hs+"</td>";')
html.append('h+="<td>"+x.fit_score.toFixed(1)+"</td>";')
html.append('h+="<td>"+bg(x.rating,x.fit_score)+"</td>";')
html.append('h+="<td style=\\"color:#888;font-size:11px;\\">\\u25bc</td></tr>";')

# Detail row
html.append('var trap=ar.trap_analysis||"";var risk=ar.key_risk||"";var s7r=ar.s7_reason||"";var ld=mc2.lambda_diff||0;')
html.append('h+="<tr class=\\"detail-row\\" id=\\"quot;+did+"\\"><td colspan=\\"12\\" style=\\"padding:0;\\"><div class=\\"detail-box\\">";')
html.append('h+="<b>\\u03bb\\u5dee\\u503c:</b> "+ld.toFixed(3);')
html.append('if(s7r){h+="<br><b>S7\\u8bf4\\u660e:</b> "+s7r}')
html.append('if(trap){h+="<br><b>\\u8bf1\\u76d8\\u5206\\u6790:</b> "+trap}')
html.append('if(risk){h+="<br><b style=\\"color:#ef5350;\\">\\u98ce\\u9669\\u63d0\\u793a:</b> "+risk}')
html.append('h+="</div></td></tr>"')
html.append('});')
html.append('h+="</tbody></table>";')
html.append('document.getElementById("result").innerHTML=h;')
html.append('}')

html.append('window.onload=function(){')
html.append('fetch("/api/latest").then(function(r){return r.json();}).then(function(d){')
html.append('if(d.rating&&d.rating.length>0){rs(d);}')
html.append('}).catch(function(){});')
html.append('};')

html.append('</script>')
html.append('</body>')
html.append('</html>')

path = "C:/Users/gjj/Desktop/v333/templates/index.html"
with open(path, "w", encoding="utf-8") as f:
    f.write("\n".join(html))
print("OK:", len("\n".join(html)))
